### ISSUE TITLE
error: possible duplicate --failfast in python 3.12

### ISSUE THREAD

**Issue by jihunkim0** [kenunq/django-neotest#1]
In python 3.12, I get below error

Traceback (most recent call last):
  File "/.local/share/nvim/lazy/django-neotest/neotest.py", line 20, in <module>
    main(sys.argv[1:])
  File "/.local/share/nvim/lazy/django-neotest/django_neotest/__init__.py", line 70, in main
    results = adapter.run(args.args, stream)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/nvim/lazy/django-neotest/django_neotest/django_unittest.py", line 142, in run
    DjangoUnittestRunner.add_arguments(parser)
  File "/.local/share/nvim/lazy/django-neotest/django_neotest/django_unittest.py", line 91, in add_arguments
    parser.add_argument(
  File "/usr/lib/python3.12/argparse.py", line 1507, in add_argument
    return self._add_action(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1889, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.12/argparse.py", line 1709, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1521, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.12/argparse.py", line 1658, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.12/argparse.py", line 1667, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --failfast: conflicting option string: --failfast

**Comment by metal3d** [comment]
Same for me
